name: Working with Environments

on:
    workflow_dispatch: 
        inputs:
            target-env:
                type: environment
                default: pre

run-name: Working with Envoiroments | env - ${{inputs.target-env}}

jobs:
    echo:
        environment: ${{inputs.target-env}}
        env:
            my_env_value:  "${{vars.MY_ENV_VALUE != '' && vars.MY_ENV_VALUE || 'default value'}}"
        runs-on: ubuntu-latest
        steps:
            - name: Echo vars
              run: |
                echo Env variable: ${{env.my_env_value}}
              